### ISSUE TITLE
config/unc.rb -- NoMethodError:undefined method 'argot_holdings_object'

### ISSUE THREAD

**Issue by kspurgin** [trln/marc-to-argot#1]
```
kspurgin@L004904:~/trln/marc-to-argot$ traject -c config/unc.rb -c argot.rb out.xml 

Error loading configuration file config/unc.rb:32 NoMethodError:undefined method `argot_holdings_object' for #<Traject::Indexer:0x00000001961a08>
config/unc.rb:32:in `block in load_config_file'

Exiting...
```

**Comment by queryluke** [comment]
That's my fault, the readme was incorrect. I just fixed it. It works when the inst config is included after argot.rb.

However, I still consider this an issue. Ideally it should not matter.

**Comment by kspurgin** [comment]
Or, if the readme is corrected and it works when you do it like the readme says... issue resolved? :-) Up to you whether to close or not.
