### ISSUE TITLE
Store items as JSON blobs

### ISSUE THREAD

**Issue by adjam** [trln/marc-to-argot#14]
As a first pass for encoding item data, we will store them as blobs of JSON with at least the following keys (ref TD-340)

id
library
shelving_location
call_number
call_number_scheme
status

It is permissible for the time being to store more keys, these are the ones that will be consumed by the Argon engine.

**Comment by queryluke** [comment]
@adjam @corylown 
I didn't realize this until this afternoon, but the [unc/traject_config.rb](https://github.com/trln/marc-to-argot/blob/master/lib/data/unc/traject_config.rb#L39) already does this for items, if anyone wants to try and mirror the code. Not sure how similar it will be for you two.
