### ISSUE TITLE
Misspelled word

### ISSUE THREAD

**Issue by bootsunc** [trln/marc-to-argot#285]
https://github.com/trln/marc-to-argot/blob/f2d8ec4c6bdbf9f6540227b97be01f2bc575b646/lib/translation_maps/shared/subject_heading_remappings.yaml#L226

immigrants not immigants

I was looking at the TRLN headings to map into OCLC and noticed the typo.  Creating a file for UNC to upload into WorldCat.
https://help.oclc.org/Discovery_and_Reference/WorldCat_Discovery/Display_local_data/Create_locally_preferred_subjects_for_display_and_search_expansion?utm_campaign=Oktopost-Corporate+-+Products+and+Services&utm_content=Oktopost-twitter&utm_medium=social&utm_source=twitter

**Comment by kellysmithfarrell** [comment]
Thanks for surfacing this. I've fixed it in the file.

**Comment by bootsunc** [comment]
Thanks for fixing #285 and #287 capitalization issue.


wkg

________________________________
